// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter, Crimson_Pro } from "next/font/google";
import "./globals.css";
import BottomNav from "@/components/custom/bottom-nav";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Fonte Crimson Pro para leitura confortável (similar à Bookerly)
const crimsonPro = Crimson_Pro({
  variable: "--font-bookerly",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bíblia Multilíngue Interativa",
  description: "Pratique sua espiritualidade e aprenda um novo idioma através da leitura da Bíblia",
  manifest: "/manifest.json",
  themeColor: "#3B82F6",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Bíblia Multilíngue",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="h-full">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </head>
      <body className={`${inter.variable} ${crimsonPro.variable} font-inter antialiased bg-[#FAF9F6] dark:bg-gray-950 h-full overflow-hidden`}>
        <div className="h-full flex flex-col">
          <div className="flex-1 overflow-hidden">
            {children}
          </div>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
