// Generated by Lasy AI - https://lasy.ai
import type { Metadata, Viewport } from "next";
import { Inter, Crimson_Pro } from "next/font/google";
import "./globals.css";
import BottomNav from "@/components/custom/bottom-nav";
import { NavigationProvider } from "@/contexts/NavigationContext";
import { Analytics } from '@vercel/analytics/react';
import CookieBanner from '@/components/custom/cookie-banner';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Fonte Crimson Pro para leitura confortável (similar à Bookerly)
const crimsonPro = Crimson_Pro({
  variable: "--font-bookerly",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bíblia Interativa - Leitura Bíblica com Áudio em Múltiplos Idiomas",
  description: "Transforme sua experiência de leitura bíblica com áudio profissional em vários idiomas, tradução em tempo real, exercícios interativos e planos de leitura personalizados. Acesse todas as versões da Bíblia gratuitamente.",
  keywords: [
    'bíblia online',
    'bíblia com áudio',
    'leitura bíblica',
    'bíblia multilíngue',
    'tradução bíblica',
    'áudio bíblia',
    'exercícios bíblicos',
    'estudo bíblico',
    'plano de leitura bíblica',
    'bíblia interativa',
  ],
  authors: [{ name: 'Bíblia Interativa' }],
  creator: 'Bíblia Interativa',
  publisher: 'Bíblia Interativa',
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Bíblia Interativa",
  },
  openGraph: {
    type: 'website',
    locale: 'pt_BR',
    url: 'https://bibliainterativa.com',
    title: 'Bíblia Interativa - Leitura Bíblica com Áudio em Múltiplos Idiomas',
    description: 'Transforme sua experiência de leitura bíblica com áudio profissional, tradução em tempo real e exercícios interativos.',
    siteName: 'Bíblia Interativa',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Bíblia Interativa - Leitura Bíblica com Áudio',
    description: 'Experiência completa de leitura bíblica com áudio em múltiplos idiomas e tradução em tempo real.',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: "#3B82F6",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" data-scroll-behavior="smooth">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, viewport-fit=cover" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </head>
      <body className={`${inter.variable} ${crimsonPro.variable} font-inter antialiased bg-[#FAF9F6] dark:bg-gray-950`}>
        <NavigationProvider>
          {children}
          <BottomNav />
        </NavigationProvider>
        <CookieBanner />
        <Analytics />
      </body>
    </html>
  );
}
